# Generated by Django 3.2.7 on 2021-10-02 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminHOD',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Created_at', models.DateField(auto_now_add=True)),
                ('Updated_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attandance',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('attandanceDate', models.DateTimeField(auto_now_add=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=255)),
                ('Created_at', models.DateField(auto_now_add=True)),
                ('Updated_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Address', models.TextField()),
                ('Created_at', models.DateField(auto_now_add=True)),
                ('Updated_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=255)),
                ('Created_at', models.DateField(auto_now_add=True)),
                ('Updated_at', models.DateField(auto_now_add=True)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementApp.courses')),
                ('staffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementApp.staffs')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=20)),
                ('Profile', models.FileField(upload_to='')),
                ('Address', models.TextField()),
                ('Created_at', models.DateField(auto_now_add=True)),
                ('Updated_at', models.DateField(auto_now_add=True)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementApp.courses')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationStudent',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationStaff',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('leaveStatus', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('staffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementApp.staffs')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveReportStudent',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('leaveDate', models.CharField(max_length=255)),
                ('leaveMessage', models.TextField()),
                ('leaveStatus', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveReportStaff',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('leaveDate', models.CharField(max_length=255)),
                ('leaveMessage', models.TextField()),
                ('leaveStatus', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('staffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementApp.staffs')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackStudent',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('feedbackReply', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackStaff',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('feedbackReply', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('staffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementApp.staffs')),
            ],
        ),
        migrations.CreateModel(
            name='AttandanceReport',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('attandanceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementApp.attandance')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentManagementApp.student')),
            ],
        ),
        migrations.AddField(
            model_name='attandance',
            name='subjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementApp.subject'),
        ),
    ]
